######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 7 09:18:13 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stdafx.h targetver.h \
    SslSocketLayer.h \
    KAES.h \
    filemark.h
SOURCES += safeImport.cpp stdafx.cpp \
    SslSocketLayer.cpp \
    KAES.cpp \
    filemark.cpp
